name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    uses: pkgjs/action/.github/workflows/node-test.yaml@v0
    with:
      post-test-steps: |
        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v1
          with:
            file: ./coverage/clover.xml
            flags: unittests
            name: lib
            fail_ci_if_error: false
